### ISSUE TITLE
Wrong link for Golden Certificate

### ISSUE THREAD

**Issue by ShutdownRepo** [zblurx/certsync#10]
Resource linked in the README for Golden Certificate is not the right one.

CertSync relies on the extraction of the CA cert private key, to forge and sign certificates (this is called Golden Certificate) in order to do UnPAC-the-hash later on.

The resource indicated in the README (https://cyberstoph.org/posts/2019/12/an-introduction-to-golden-certificates/) refers to a different technique, but called the same. The technique shown in the post relies on DPERSIST3, where the attacker has enough privileges against a certificate template, to modify it and make it a SmartCard certificate template.

More info: https://www.thehacker.recipes/ad/persistence/ad-cs/golden-certificate

**Comment by zblurx** [comment]
Fixed in 9c53ff7eb90ed13e40e509cf78fe07eae684fb1b
I put your link !
