### ISSUE TITLE
cryptography.exceptions.UnsupportedAlgorithm: Hash algorithm "sha1" not supported for signatures

### ISSUE THREAD

**Issue by n00py** [zblurx/certsync#11]
Was trying to use this and kept getting this error:

` File "/usr/local/lib/python3.9/dist-packages/certsync/entry.py", line 610, in main
    certsync.run()
  File "/usr/local/lib/python3.9/dist-packages/certsync/entry.py", line 237, in run
    user.forge_cert(key=base_user_key, cert=base_user_cert, ca_key=self.ca_key, ca_cert=self.ca_cert)
  File "/usr/local/lib/python3.9/dist-packages/certsync/entry.py", line 64, in forge_cert
    cert = cert.sign(ca_key, signature_hash_algorithm())
  File "/usr/local/lib/python3.9/dist-packages/cryptography/x509/base.py", line 940, in sign
    return rust_x509.create_x509_certificate(self, private_key, algorithm)
cryptography.exceptions.UnsupportedAlgorithm: Hash algorithm "sha1" not supported for signatures
`

I was able to fix with:

python3.9 -m pip install  cryptography==38.0.1

Apparently python crypto library removed support for SHA1

**Comment by zblurx** [comment]
Hey @n00py, thank you for the issue !
I can't reproduce with python 3.9.2, what is your openssl version ? I'm running on `OpenSSL 1.1.1n  15 Mar 2022`.
Also, maybe upgrading certipy-ad to 4.7.0 might fix this openssl issue
