### ISSUE TITLE
couldn't dumped

### ISSUE THREAD

**Issue by hashurt** [zblurx/certsync#15]
There is such a situation, its a test evironment, Before i could get the hashes with this user. after i reinstalled the certificate server and configured it but now icouldt get the hashes with same user.

└─$ certsync -u Administrator -p 'passpass' -d test.local -dc-ip 10.10.10.10 -ns 10.10.10.10 -debug
[*] Collecting userlist, CA info and CRL on LDAP
[*] Found 15 users in LDAP
[*] Found CA test-WIN-abcabc-CA on WIN-abcabc.test.local(10.10.10.10)
[*] Dumping CA certificate and private key
[+] Creating new service
[+] Creating backup
[+] Retrieving backup
[+] Cleaning up
[*] Forging certificates for every users. This can take some time...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 987.45it/s]
[*] PKINIT + UnPAC the hashes
[+] **0 users dumped. 15 users could not be dumped.**

Is this caused by pkinit? how could i set up test environment for this tool on active directory?

**Comment by zblurx** [comment]
Hey, this might be because your lab does not support pkinit. You should renew the machine certificate of your DC
