### ISSUE TITLE
Authenticating using a CA certificate and matching private key

### ISSUE THREAD

**Issue by jsdhasfedssad** [zblurx/certsync#2]
Hi,

Thank you for this tool!

I am having trouble authenticating using a CA certificate and it's matching private key which I dumped from the ADCS server using Certipy beforehand. What am I doing wrong?

![certsync1](https://user-images.githubusercontent.com/97032878/216048949-b2ba74c9-1007-408f-8edd-0d4df2198605.png)

**Comment by zblurx** [comment]
Hey,

The `-ca-pfx` flag is used to skip the CA private key dump phase of the attack, but you need to use a valid user account in certsync to request LDAP. However, if you use -ca-pfx, you only need a standard user account, not even CA administrator.

**Comment by jsdhasfedssad** [comment]
Great. It works. Thanks.
