### ISSUE TITLE
'NoneType' object has no attribute 'subject'

### ISSUE THREAD

**Issue by dodiorne** [zblurx/certsync#4]
testing this out and getting the above error from multiple CA servers.  here is the full command i'm running with debug output.

└─$ python3 entry.py -u xxxx-p "xxxxxxx" -d xxxxx -dc-ip x.x.x.x -ns x.x.x.x -debug
[*] Collecting userlist, CA info and CRL on LDAP
[*] Found 1xxxxx users in LDAP
[-] Too much CA, need to select one specific
[*] Please select one:
        [0] xxxxx
        [1] xxxxxx
        [2] xxxxx
        [3] xxxxx
> 3
[*] Found CA xxxxx on xxxxxxxx
[*] Dumping CA certificate and private key
[-] Failed to connect to Service Control Manager Remote Protocol
[*] Forging certificates for every users. This can take some time...
[-] Got error: 'NoneType' object has no attribute 'subject'
Traceback (most recent call last):
  File "/home/kali/certsync/certsync/entry.py", line 602, in main
    certsync.run()
  File "/home/kali/certsync/certsync/entry.py", line 229, in run
    base_user_key, base_user_cert = self.forge_cert_base()
  File "/home/kali/certsync/certsync/entry.py", line 254, in forge_cert_base
    cert = cert.issuer_name(self.ca_cert.subject)
AttributeError: 'NoneType' object has no attribute 'subject'

**Comment by zblurx** [comment]
Hey, looks like the CA you are targeting does not exists anymore. Can you check if you can `certipy ca -backup` ([more info here](https://github.com/ly4k/Certipy#golden-certificates)) properly ?
