### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [zblurx/certsync#7]
Hello Team, 

I have updated my Kali Linux and it seems Python has also updated to 3.11.2. When I run the command it throws an error 

```
certsync -d adlab.com -u Administrator -hashes aad3b435b51404eeaad3b435b51404ee:64cbb76dcafe2e977794f6251f8231fb -dc-ip 192.168.126.146 -randomize -ldap-filter "(&(|(objectCategory=person)))" -debug
[*] Collecting userlist, CA info and CRL on LDAP
[*] Found 5 users in LDAP
[*] Found CA adlab-WIN-3MBDJTT1P21-CA on WIN-3MBDJTT1P21.adlab.com(192.168.126.146)
[*] Dumping CA certificate and private key
[-] Got error: 'list' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/certsync/entry.py", line 608, in main
    certsync.run()
  File "/home/kali/.local/lib/python3.11/site-packages/certsync/entry.py", line 206, in run
    ca_target = Target.create(
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.4.0-py3.11.egg/certipy/lib/target.py", line 339, in create
    hashes = hashes.split(":")
             ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'

```

Python version 
python3 --version
Python 3.11.2

Also, I have updated my certipy to 4.4.0

![image](https://user-images.githubusercontent.com/7692857/231351387-29594656-cee0-48cf-ad33-7df381038d45.png)

**Comment by Cyb3rGh0st786** [comment]
Also, can we specifically target a user by passing its user name rather than dumping all the users 

It would be a good idea for opsec concerns to reduce the traffic

**Comment by zblurx** [comment]
> Hello Team,
> 
> I have updated my Kali Linux and it seems Python has also updated to 3.11.2. When I run the command it throws an error
> 
> ```
> certsync -d adlab.com -u Administrator -hashes aad3b435b51404eeaad3b435b51404ee:64cbb76dcafe2e977794f6251f8231fb -dc-ip 192.168.126.146 -randomize -ldap-filter "(&(|(objectCategory=person)))" -debug
> [*] Collecting userlist, CA info and CRL on LDAP
> [*] Found 5 users in LDAP
> [*] Found CA adlab-WIN-3MBDJTT1P21-CA on WIN-3MBDJTT1P21.adlab.com(192.168.126.146)
> [*] Dumping CA certificate and private key
> [-] Got error: 'list' object has no attribute 'split'
> Traceback (most recent call last):
>   File "/home/kali/.local/lib/python3.11/site-packages/certsync/entry.py", line 608, in main
>     certsync.run()
>   File "/home/kali/.local/lib/python3.11/site-packages/certsync/entry.py", line 206, in run
>     ca_target = Target.create(
>                 ^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.4.0-py3.11.egg/certipy/lib/target.py", line 339, in create
>     hashes = hashes.split(":")
>              ^^^^^^^^^^^^
> AttributeError: 'list' object has no attribute 'split'
> ```
> 
> Python version python3 --version Python 3.11.2
> 
> Also, I have updated my certipy to 4.4.0
> 
> ![image](https://user-images.githubusercontent.com/7692857/231351387-29594656-cee0-48cf-ad33-7df381038d45.png)

Hey, seems like you have certipy-ad 4.4.0 installed, and for now certsync only support certipy-ad 4.3.0. So in order to avoid dependency conflicts, you should use [pipx](https://github.com/pypa/pipx) to install your python tools.

Nevertheless, i will soon update certsync to support certipy 4.4.0.

> Also, can we specifically target a user by passing its user name rather than dumping all the users
> 
> It would be a good idea for opsec concerns to reduce the traffic

[Already implemented](https://github.com/zblurx/certsync#opsec)

**Comment by Cyb3rGh0st786** [comment]
Thank you, @zblurx, for your response. 

Can I specify only one user name? For example, I want to retrieve the hash for "administrator", not for any other user. I did not find the flag for it. The below command dump all the user hashes.

```
certsync -u administrator  -d adlab.com -dc-ip 192.168.126.146 -ns 192.168.126.146 -randomize -ldap-filter "(&(|(objectCategory=person))(objectClass=user))"
```

**Comment by zblurx** [comment]
> 
You should try with `-ldap-filter '(SAMAccountname=administrator)'`

I've just uploaded the tool (deleted setup.py and upgrade certipy-ad basically), you can install it with `pipx install git+https://github.com/zblurx/certsync`. Let me know

**Comment by Cyb3rGh0st786** [comment]
Thank you for the support, and it worked.
