### ISSUE TITLE
'list' object has no attribute 'split' when choosing multiple CIs

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [zblurx/certsync#8]
Hello Team, 

During one of the assessments, it was observed that the org has multiple CIs and asked to choose one when I select and got an error 

[*] Found 1 user in LDAP
[-] Too much CA, need to select one specific
[*] Please select one:
        [0] ISSUING-test1 at test1.adblab.com
        [1] ISSUING-test2 at test2.adblab.com
        [2] Issuing-test3 at test3.adblab.com
    
> 2
[*] Found CA ISSUING-test2 on test2.adblab.com
[*] Dumping CA certificate and private key
[-] Got error: 'list' object has no attribute 'split'
[-] Use -debug to print a stacktrace

I have used both on certipy v 4.4 and 4.3 and python version 3.10 and 3.11 but still got the same error. It would be great if you can help on this

**Comment by zblurx** [comment]
Hey, can you provide a debug trace with `-debug` and the output of `certipy find` command please ?
My guess is that the CA you are trying to dump does not exists anymore, but is still in LDAP for maintanability purpose.

**Comment by Cyb3rGh0st786** [comment]
@zblurx  I can confirm those CAs exist, and I have changed the names in this ticket. 

[*] Dumping CA certificate and private key
[-] Got error: 'list' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/certsync-0.1.0-py3.10.egg/certsync/entry.py", line 608, in main
    certsync.run()
  File "/usr/local/lib/python3.10/dist-packages/certsync-0.1.0-py3.10.egg/certsync/entry.py", line 206, in run
    ca_target = Target.create(
  File "/usr/local/lib/python3.10/dist-packages/certipy_ad-4.3.0-py3.10.egg/certipy/lib/target.py", line 339, in create
    hashes = hashes.split(":")
AttributeError: 'list' object has no attribute 'split'

**Comment by Cyb3rGh0st786** [comment]
this is another environment where I am using certipy 4.4 and python 3.11.2

[-] Got error: 'list' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/kali/.local/pipx/venvs/certsync/lib/python3.11/site-packages/certsync/entry.py", line 608, in main
    certsync.run()
  File "/home/kali/.local/pipx/venvs/certsync/lib/python3.11/site-packages/certsync/entry.py", line 206, in run
    ca_target = Target.create(
                ^^^^^^^^^^^^^^
  File "/home/kali/.local/pipx/venvs/certsync/lib/python3.11/site-packages/certipy/lib/target.py", line 339, in create
    hashes = hashes.split(":")
             ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
                                                                                                                                                                                                         
┌──(kali㉿kali)-[~/Desktop/tools]
└─$ cetipy -v
Command 'cetipy' not found, did you mean:
  command 'certipy' from deb python3-certipy
Try: sudo apt install <deb name>
                                                                                                                                                                                                         
┌──(kali㉿kali)-[~/Desktop/tools]
└─$ certipy -v                                                                                     
Certipy v4.4.0 - by Oliver Lyak (ly4k)

                                                                                                                                                                                                         
┌──(kali㉿kali)-[~/Desktop/tools]
└─$ python                  
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by zblurx** [comment]
Looks like you submitted an invalid hash in the command line. Try put it with `:<nthash>`

**Comment by Cyb3rGh0st786** [comment]
Hello @zblurx ,

I have used the nthash as suggested, but I still have the same error, and the hash is valid.

**Comment by zblurx** [comment]
Can you give me the command line ? Even anonymized

**Comment by Cyb3rGh0st786** [comment]
certsync -u test -hashes nthash -dc-ip 1.2.4.3 -d test.adlab.com -randomize -ldap-filter '(SAMAccountname=usertest)' -debug

**Comment by zblurx** [comment]
Try it like that `certsync -u test -hashes ':nthash' -dc-ip 1.2.4.3 -d test.adlab.com -randomize -ldap-filter '(SAMAccountname=usertest)' -debug`. Note the column before the nthash

**Comment by Cyb3rGh0st786** [comment]
Hello @zblurx , I have tried and got the same error.

**Comment by zblurx** [comment]
Ok. Thanks for the debugging. I have managed to reproduce the issue and pushed a fix. Please update the code with  `pipx install git+https://github.com/zblurx/certsync --force`

**Comment by Cyb3rGh0st786** [comment]
Hello @zblurx , 

I don't see the issue now, but in the end, there will not be any hash dumped for the user I specified. what could be the reason for that?

**Comment by zblurx** [comment]
If your user is revoked, it wont dump its hash.
Also, if the ldap filter is incorrect, it will say that no user were found in LDAP

**Comment by Cyb3rGh0st786** [comment]
thank you
